// flow-typed signature: ad7ae51ae9d8d87274688b0e3bfd349a
// flow-typed version: <<STUB>>/xenvar_v~0.5.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xenvar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xenvar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xenvar/Gruntfile' {
  declare module.exports: any;
}

declare module 'xenvar/lib/xenvar' {
  declare module.exports: any;
}

declare module 'xenvar/test/xenvar_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xenvar/Gruntfile.js' {
  declare module.exports: $Exports<'xenvar/Gruntfile'>;
}
declare module 'xenvar/lib/xenvar.js' {
  declare module.exports: $Exports<'xenvar/lib/xenvar'>;
}
declare module 'xenvar/test/xenvar_test.js' {
  declare module.exports: $Exports<'xenvar/test/xenvar_test'>;
}
